In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Salaries.csv to Salaries.csv


In [ ]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:.3f}'.format
df = pd.read_csv("Salaries.csv")
df


<ipython-input-4-d592aed79f65>:4: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Salaries.csv")


Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle       BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY    167411.180   
1                      CAPTAIN III (POLICE DEPARTMENT)    155966.020   
2                      CAPTAIN III (POLICE DEPARTMENT)    212739.130   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC     77916.000   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)    134401.600   
...                                                ...           ...   
148649                                       Custodian          0.00   
148650                                    Not provided  Not Provided   
148651                                    Not provided  Not Provided   
148652                                    Not provided  Not Provided   
148653                      Counselor, Log Cabin Ranch          0.00   

         OvertimePay      OtherPay      Benefits   TotalPay  TotalPayBenefits  \
0              0.000    400184.250           NaN 567595.430        567595.430   
1         245131.880    137811.380           NaN 538909.280        538909.280   
2         106088.180     16452.600           NaN 335279.910        335279.910   
3          56120.710    198306.900           NaN 332343.610        332343.610   
4           9737.000    182234.590           NaN 326373.190        326373.190   
...              ...           ...           ...        ...               ...   
148649          0.00          0.00          0.00      0.000             0.000   
148650  Not Provided  Not Provided  Not Provided      0.000             0.000   
148651  Not Provided  Not Provided  Not Provided      0.000             0.000   
148652  Not Provided  Not Provided  Not Provided      0.000             0.000   
148653          0.00       -618.13          0.00   -618.130          -618.130   

        Year  Notes         Agency Status  
0       2011    NaN  San Francisco    NaN  
1       2011    NaN  San Francisco    NaN  
2       2011    NaN  San Francisco    NaN  
3       2011    NaN  San Francisco    NaN  
4       2011    NaN  San Francisco    NaN  
...      ...    ...            ...    ...  
148649  2014    NaN  San Francisco     PT  
148650  2014    NaN  San Francisco    NaN  
148651  2014    NaN  San Francisco    NaN  
148652  2014    NaN  San Francisco    NaN  
148653  2014    NaN  San Francisco     PT  

[148654 rows x 13 columns]

In [ ]:
# returns the  description of the dataframe
df.describe()

Id   TotalPay  TotalPayBenefits       Year  Notes
count 148654.000 148654.000        148654.000 148654.000  0.000
mean   74327.500  74768.322         93692.555   2012.523    NaN
std    42912.858  50517.005         62793.533      1.118    NaN
min        1.000   -618.130          -618.130   2011.000    NaN
25%    37164.250  36168.995         44065.650   2012.000    NaN
50%    74327.500  71426.610         92404.090   2013.000    NaN
75%   111490.750 105839.135        132876.450   2014.000    NaN
max   148654.000 567595.430        567595.430   2014.000    NaN

In [ ]:
#returns the first 5 entries by default, we can pass parameter in the method to get those particular number of entries.
df.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay OvertimePay   OtherPay Benefits   TotalPay  TotalPayBenefits  \
0 167411.180       0.000 400184.250      NaN 567595.430        567595.430   
1 155966.020  245131.880 137811.380      NaN 538909.280        538909.280   
2 212739.130  106088.180  16452.600      NaN 335279.910        335279.910   
3  77916.000   56120.710 198306.900      NaN 332343.610        332343.610   
4 134401.600    9737.000 182234.590      NaN 326373.190        326373.190   

   Year  Notes         Agency Status  
0  2011    NaN  San Francisco    NaN  
1  2011    NaN  San Francisco    NaN  
2  2011    NaN  San Francisco    NaN  
3  2011    NaN  San Francisco    NaN  
4  2011    NaN  San Francisco    NaN

In [ ]:
#returns the last 5 entries of the dataset, we can pass parameter to get certain number of entries from the end.
df.tail()

Id   EmployeeName                    JobTitle       BasePay  \
148649  148650  Roy I Tillery                   Custodian          0.00   
148650  148651   Not provided                Not provided  Not Provided   
148651  148652   Not provided                Not provided  Not Provided   
148652  148653   Not provided                Not provided  Not Provided   
148653  148654      Joe Lopez  Counselor, Log Cabin Ranch          0.00   

         OvertimePay      OtherPay      Benefits  TotalPay  TotalPayBenefits  \
148649          0.00          0.00          0.00     0.000             0.000   
148650  Not Provided  Not Provided  Not Provided     0.000             0.000   
148651  Not Provided  Not Provided  Not Provided     0.000             0.000   
148652  Not Provided  Not Provided  Not Provided     0.000             0.000   
148653          0.00       -618.13          0.00  -618.130          -618.130   

        Year  Notes         Agency Status  
148649  2014    NaN  San Francisco     PT  
148650  2014    NaN  San Francisco    NaN  
148651  2014    NaN  San Francisco    NaN  
148652  2014    NaN  San Francisco    NaN  
148653  2014    NaN  San Francisco     PT

In [ ]:
#isnull() returns a dataset containing true/false, true indicates that the corresponding value in the dataset is null.
missing_values = df.isnull()
missing_values

Id  EmployeeName  JobTitle  BasePay  OvertimePay  OtherPay  \
0       False         False     False    False        False     False   
1       False         False     False    False        False     False   
2       False         False     False    False        False     False   
3       False         False     False    False        False     False   
4       False         False     False    False        False     False   
...       ...           ...       ...      ...          ...       ...   
148649  False         False     False    False        False     False   
148650  False         False     False    False        False     False   
148651  False         False     False    False        False     False   
148652  False         False     False    False        False     False   
148653  False         False     False    False        False     False   

        Benefits  TotalPay  TotalPayBenefits   Year  Notes  Agency  Status  
0           True     False             False  False   True   False    True  
1           True     False             False  False   True   False    True  
2           True     False             False  False   True   False    True  
3           True     False             False  False   True   False    True  
4           True     False             False  False   True   False    True  
...          ...       ...               ...    ...    ...     ...     ...  
148649     False     False             False  False   True   False   False  
148650     False     False             False  False   True   False    True  
148651     False     False             False  False   True   False    True  
148652     False     False             False  False   True   False    True  
148653     False     False             False  False   True   False   False  

[148654 rows x 13 columns]

In [ ]:
missing_values_count = df.isnull().sum()
print(missing_values_count)

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                605
OvertimePay              0
OtherPay                 0
Benefits             36159
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              110535
dtype: int64


In [ ]:
#tells the field name and the corresponding data type.
variable_descriptions = df.dtypes
print(variable_descriptions)

Id                    int64
EmployeeName         object
JobTitle             object
BasePay              object
OvertimePay          object
OtherPay             object
Benefits             object
TotalPay            float64
TotalPayBenefits    float64
Year                  int64
Notes               float64
Agency               object
Status               object
dtype: object


In [ ]:
print(df["Benefits"].unique())

[nan 44430.12 69810.19 ... '0.13' '1.24' 'Not Provided']


In [ ]:
df['Benefits'] = df['Benefits'].replace('Not Provided', np.nan)
df['Benefits'] = df['Benefits'].astype(float)
print(df['Benefits'].unique())

[         nan 4.443012e+04 6.981019e+04 ... 2.200000e-01 1.300000e-01
 1.240000e+00]


In [ ]:
df.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0 167411.180       0.000 400184.250       NaN 567595.430        567595.430   
1 155966.020  245131.880 137811.380       NaN 538909.280        538909.280   
2 212739.130  106088.180  16452.600       NaN 335279.910        335279.910   
3  77916.000   56120.710 198306.900       NaN 332343.610        332343.610   
4 134401.600    9737.000 182234.590       NaN 326373.190        326373.190   

   Year  Notes         Agency Status  
0  2011    NaN  San Francisco    NaN  
1  2011    NaN  San Francisco    NaN  
2  2011    NaN  San Francisco    NaN  
3  2011    NaN  San Francisco    NaN  
4  2011    NaN  San Francisco    NaN

In [ ]:
df["BasePay"].unique()

array([167411.18, 155966.02, 212739.13, ..., '6.04', '15.50',
       'Not Provided'], dtype=object)

In [ ]:
#Cleaning base pay -> converting not provided into missing values and rest of string values into float values
df["BasePay"].replace('Not Provided', np.nan, inplace =True)
df["BasePay"] = df["BasePay"].astype(float)
print(df["BasePay"].unique())

[1.6741118e+05 1.5596602e+05 2.1273913e+05 ... 1.7260000e+01 6.0400000e+00
 1.5500000e+01]


In [ ]:
df["BasePay"].unique()

array([1.6741118e+05, 1.5596602e+05, 2.1273913e+05, ..., 1.7260000e+01,
       6.0400000e+00, 1.5500000e+01])

In [ ]:
#Cleaning overitme pay -> converting not provided into missing values and rest of string values into float values
df["OvertimePay"].unique()
df["OvertimePay"].replace('Not Provided', np.nan, inplace= True)
df["OvertimePay"] = df["OvertimePay"].astype(float)
df["OvertimePay"].unique()

array([0.0000000e+00, 2.4513188e+05, 1.0608818e+05, ..., 1.0270000e+02,
       5.6770000e+01,           nan])

In [ ]:
df["OtherPay"].unique()

array([400184.25, 137811.38, 16452.6, ..., '13.35', 'Not Provided',
       '-618.13'], dtype=object)

In [ ]:
#Cleaning other pay -> converting not provided into missing values and rest of string values into float values
df["OtherPay"].replace('Not Provided', np.nan, inplace=True)
df["OtherPay"] = df["OtherPay"].astype(float)
df["OtherPay"].unique()

array([ 4.0018425e+05,  1.3781138e+05,  1.6452600e+04, ...,
        1.5350000e+01,            nan, -6.1813000e+02])

In [ ]:
df["Agency"].unique()

array(['San Francisco'], dtype=object)

In [ ]:
df["Agency"] = df["Agency"].astype('|S')
df["Agency"]

0         b'San Francisco'
1         b'San Francisco'
2         b'San Francisco'
3         b'San Francisco'
4         b'San Francisco'
                ...       
148649    b'San Francisco'
148650    b'San Francisco'
148651    b'San Francisco'
148652    b'San Francisco'
148653    b'San Francisco'
Name: Agency, Length: 148654, dtype: bytes104

In [ ]:
df.dtypes

Id                    int64
EmployeeName         object
JobTitle             object
BasePay             float64
OvertimePay         float64
OtherPay            float64
Benefits            float64
TotalPay            float64
TotalPayBenefits    float64
Year                  int64
Notes               float64
Agency                 |S13
Status               object
dtype: object

In [ ]:
df["BasePay"].unique()

array([1.6741118e+05, 1.5596602e+05, 2.1273913e+05, ..., 1.7260000e+01,
       6.0400000e+00, 1.5500000e+01])

In [ ]:
#dropping all the records with missing values and replacing the 
df.dropna(subset=['BasePay'], inplace=True)
df.isnull().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                  0
OvertimePay              0
OtherPay                 0
Benefits             36159
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148045
Agency                   0
Status              109926
dtype: int64

In [ ]:
df.dropna(subset=['Benefits'], inplace=True)
# reset index, because we droped two rows
df.reset_index(drop=True, inplace=True)
df


Id        EmployeeName                      JobTitle    BasePay  \
0        36160      Gary Altenberg  Lieutenant, Fire Suppression 128808.870   
1        36161        Gregory Suhr               Chief of Police 302578.000   
2        36162          Khoa Trinh   Electronic Maintenance Tech 111921.000   
3        36163  Joanne Hayes-White        Chief, Fire Department 296943.010   
4        36164   Frederick Binkley     EMT/Paramedic/Firefighter 126863.190   
...        ...                 ...                           ...        ...   
111881  148646    Carolyn A Wilson     Human Services Technician      0.000   
111882  148648      Joann Anderson   Communications Dispatcher 2      0.000   
111883  148649         Leon Walker                     Custodian      0.000   
111884  148650       Roy I Tillery                     Custodian      0.000   
111885  148654           Joe Lopez    Counselor, Log Cabin Ranch      0.000   

        OvertimePay  OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0        220909.480 13126.310 44430.120 362844.660        407274.780  2012   
1             0.000 18974.110 69810.190 321552.110        391362.300  2012   
2        146415.320 78057.410 53102.290 336393.730        389496.020  2012   
3             0.000 17816.590 72047.880 314759.600        386807.480  2012   
4        192424.490 17917.180 44438.250 337204.860        381643.110  2012   
...             ...       ...       ...        ...               ...   ...   
111881        0.000     0.000     0.000      0.000             0.000  2014   
111882        0.000     0.000     0.000      0.000             0.000  2014   
111883        0.000     0.000     0.000      0.000             0.000  2014   
111884        0.000     0.000     0.000      0.000             0.000  2014   
111885        0.000  -618.130     0.000   -618.130          -618.130  2014   

        Notes            Agency  Status  NormalizedBasePay  
0         NaN  b'San Francisco'       2              0.404  
1         NaN  b'San Francisco'       2              0.948  
2         NaN  b'San Francisco'       2              0.351  
3         NaN  b'San Francisco'       2              0.930  
4         NaN  b'San Francisco'       2              0.398  
...       ...               ...     ...                ...  
111881    NaN  b'San Francisco'       1              0.001  
111882    NaN  b'San Francisco'       1              0.001  
111883    NaN  b'San Francisco'       1              0.001  
111884    NaN  b'San Francisco'       1              0.001  
111885    NaN  b'San Francisco'       1              0.001  

[111886 rows x 14 columns]

In [ ]:
df.isnull().sum()

Id                        0
EmployeeName              0
JobTitle                  0
BasePay                   0
OvertimePay               0
OtherPay                  0
Benefits                  0
TotalPay                  0
TotalPayBenefits          0
Year                      0
Notes                111886
Agency                    0
Status                    0
NormalizedBasePay         0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Create an instance of LabelEncoder
label_encoder = LabelEncoder()

# Fit and transform the categorical variable
df['Status'] = label_encoder.fit_transform(df['Status'])
df


Id        EmployeeName                      JobTitle    BasePay  \
36159    36160      Gary Altenberg  Lieutenant, Fire Suppression 128808.870   
36160    36161        Gregory Suhr               Chief of Police 302578.000   
36161    36162          Khoa Trinh   Electronic Maintenance Tech 111921.000   
36162    36163  Joanne Hayes-White        Chief, Fire Department 296943.010   
36163    36164   Frederick Binkley     EMT/Paramedic/Firefighter 126863.190   
...        ...                 ...                           ...        ...   
148645  148646    Carolyn A Wilson     Human Services Technician      0.000   
148647  148648      Joann Anderson   Communications Dispatcher 2      0.000   
148648  148649         Leon Walker                     Custodian      0.000   
148649  148650       Roy I Tillery                     Custodian      0.000   
148653  148654           Joe Lopez    Counselor, Log Cabin Ranch      0.000   

        OvertimePay  OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
36159    220909.480 13126.310 44430.120 362844.660        407274.780  2012   
36160         0.000 18974.110 69810.190 321552.110        391362.300  2012   
36161    146415.320 78057.410 53102.290 336393.730        389496.020  2012   
36162         0.000 17816.590 72047.880 314759.600        386807.480  2012   
36163    192424.490 17917.180 44438.250 337204.860        381643.110  2012   
...             ...       ...       ...        ...               ...   ...   
148645        0.000     0.000     0.000      0.000             0.000  2014   
148647        0.000     0.000     0.000      0.000             0.000  2014   
148648        0.000     0.000     0.000      0.000             0.000  2014   
148649        0.000     0.000     0.000      0.000             0.000  2014   
148653        0.000  -618.130     0.000   -618.130          -618.130  2014   

        Notes            Agency  Status  
36159     NaN  b'San Francisco'       2  
36160     NaN  b'San Francisco'       2  
36161     NaN  b'San Francisco'       2  
36162     NaN  b'San Francisco'       2  
36163     NaN  b'San Francisco'       2  
...       ...               ...     ...  
148645    NaN  b'San Francisco'       1  
148647    NaN  b'San Francisco'       1  
148648    NaN  b'San Francisco'       1  
148649    NaN  b'San Francisco'       1  
148653    NaN  b'San Francisco'       1  

[111886 rows x 13 columns]

In [ ]:
df["Status"].unique()

array([2, 1, 0])

In [ ]:
df.isnull().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                  0
OvertimePay              0
OtherPay                 0
Benefits                 0
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               111886
Agency                   0
Status                   0
dtype: int64

In [ ]:
df.head()

Id        EmployeeName                      JobTitle    BasePay  \
0  36160      Gary Altenberg  Lieutenant, Fire Suppression 128808.870   
1  36161        Gregory Suhr               Chief of Police 302578.000   
2  36162          Khoa Trinh   Electronic Maintenance Tech 111921.000   
3  36163  Joanne Hayes-White        Chief, Fire Department 296943.010   
4  36164   Frederick Binkley     EMT/Paramedic/Firefighter 126863.190   

   OvertimePay  OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  Notes  \
0   220909.480 13126.310 44430.120 362844.660        407274.780  2012    NaN   
1        0.000 18974.110 69810.190 321552.110        391362.300  2012    NaN   
2   146415.320 78057.410 53102.290 336393.730        389496.020  2012    NaN   
3        0.000 17816.590 72047.880 314759.600        386807.480  2012    NaN   
4   192424.490 17917.180 44438.250 337204.860        381643.110  2012    NaN   

             Agency  Status  NormalizedBasePay  
0  b'San Francisco'       2              0.404  
1  b'San Francisco'       2              0.948  
2  b'San Francisco'       2              0.351  
3  b'San Francisco'       2              0.930  
4  b'San Francisco'       2              0.398

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
column_values = df['BasePay'].values.reshape(-1, 1)
normalized_values = scaler.fit_transform(column_values)
df['NormalizedBasePay'] = normalized_values


In [ ]:
df

Id        EmployeeName                      JobTitle    BasePay  \
0        36160      Gary Altenberg  Lieutenant, Fire Suppression 128808.870   
1        36161        Gregory Suhr               Chief of Police 302578.000   
2        36162          Khoa Trinh   Electronic Maintenance Tech 111921.000   
3        36163  Joanne Hayes-White        Chief, Fire Department 296943.010   
4        36164   Frederick Binkley     EMT/Paramedic/Firefighter 126863.190   
...        ...                 ...                           ...        ...   
111881  148646    Carolyn A Wilson     Human Services Technician      0.000   
111882  148648      Joann Anderson   Communications Dispatcher 2      0.000   
111883  148649         Leon Walker                     Custodian      0.000   
111884  148650       Roy I Tillery                     Custodian      0.000   
111885  148654           Joe Lopez    Counselor, Log Cabin Ranch      0.000   

        OvertimePay  OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0        220909.480 13126.310 44430.120 362844.660        407274.780  2012   
1             0.000 18974.110 69810.190 321552.110        391362.300  2012   
2        146415.320 78057.410 53102.290 336393.730        389496.020  2012   
3             0.000 17816.590 72047.880 314759.600        386807.480  2012   
4        192424.490 17917.180 44438.250 337204.860        381643.110  2012   
...             ...       ...       ...        ...               ...   ...   
111881        0.000     0.000     0.000      0.000             0.000  2014   
111882        0.000     0.000     0.000      0.000             0.000  2014   
111883        0.000     0.000     0.000      0.000             0.000  2014   
111884        0.000     0.000     0.000      0.000             0.000  2014   
111885        0.000  -618.130     0.000   -618.130          -618.130  2014   

        Notes            Agency  Status  NormalizedBasePay  
0         NaN  b'San Francisco'       2              0.404  
1         NaN  b'San Francisco'       2              0.948  
2         NaN  b'San Francisco'       2              0.351  
3         NaN  b'San Francisco'       2              0.930  
4         NaN  b'San Francisco'       2              0.398  
...       ...               ...     ...                ...  
111881    NaN  b'San Francisco'       1              0.001  
111882    NaN  b'San Francisco'       1              0.001  
111883    NaN  b'San Francisco'       1              0.001  
111884    NaN  b'San Francisco'       1              0.001  
111885    NaN  b'San Francisco'       1              0.001  

[111886 rows x 14 columns]

In [ ]:
overtime_pay_min = df["OvertimePay"].min()
overtime_pay_max = df["OvertimePay"].max()

df["NormalizedOvertimePay"] = (df["OvertimePay"] - overtime_pay_min) / (overtime_pay_max - overtime_pay_min)
df

Id        EmployeeName                      JobTitle    BasePay  \
0        36160      Gary Altenberg  Lieutenant, Fire Suppression 128808.870   
1        36161        Gregory Suhr               Chief of Police 302578.000   
2        36162          Khoa Trinh   Electronic Maintenance Tech 111921.000   
3        36163  Joanne Hayes-White        Chief, Fire Department 296943.010   
4        36164   Frederick Binkley     EMT/Paramedic/Firefighter 126863.190   
...        ...                 ...                           ...        ...   
111881  148646    Carolyn A Wilson     Human Services Technician      0.000   
111882  148648      Joann Anderson   Communications Dispatcher 2      0.000   
111883  148649         Leon Walker                     Custodian      0.000   
111884  148650       Roy I Tillery                     Custodian      0.000   
111885  148654           Joe Lopez    Counselor, Log Cabin Ranch      0.000   

        OvertimePay  OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0        220909.480 13126.310 44430.120 362844.660        407274.780  2012   
1             0.000 18974.110 69810.190 321552.110        391362.300  2012   
2        146415.320 78057.410 53102.290 336393.730        389496.020  2012   
3             0.000 17816.590 72047.880 314759.600        386807.480  2012   
4        192424.490 17917.180 44438.250 337204.860        381643.110  2012   
...             ...       ...       ...        ...               ...   ...   
111881        0.000     0.000     0.000      0.000             0.000  2014   
111882        0.000     0.000     0.000      0.000             0.000  2014   
111883        0.000     0.000     0.000      0.000             0.000  2014   
111884        0.000     0.000     0.000      0.000             0.000  2014   
111885        0.000  -618.130     0.000   -618.130          -618.130  2014   

        Notes            Agency  Status  NormalizedBasePay  \
0         NaN  b'San Francisco'       2              0.404   
1         NaN  b'San Francisco'       2              0.948   
2         NaN  b'San Francisco'       2              0.351   
3         NaN  b'San Francisco'       2              0.930   
4         NaN  b'San Francisco'       2              0.398   
...       ...               ...     ...                ...   
111881    NaN  b'San Francisco'       1              0.001   
111882    NaN  b'San Francisco'       1              0.001   
111883    NaN  b'San Francisco'       1              0.001   
111884    NaN  b'San Francisco'       1              0.001   
111885    NaN  b'San Francisco'       1              0.001   

        NormalizedOvertimePay  
0                       1.000  
1                       0.000  
2                       0.663  
3                       0.000  
4                       0.871  
...                       ...  
111881                  0.000  
111882                  0.000  
111883                  0.000  
111884                  0.000  
111885                  0.000  

[111886 rows x 15 columns]

In [ ]:
# Z-score normalization technique->(x - mean) / std

benefits_mean = df["Benefits"].mean()
benefits_std = df["Benefits"].std()

df["Normalized_Benefits"] = (df["Benefits"] - benefits_mean) / benefits_std
df

Id        EmployeeName                      JobTitle    BasePay  \
0        36160      Gary Altenberg  Lieutenant, Fire Suppression 128808.870   
1        36161        Gregory Suhr               Chief of Police 302578.000   
2        36162          Khoa Trinh   Electronic Maintenance Tech 111921.000   
3        36163  Joanne Hayes-White        Chief, Fire Department 296943.010   
4        36164   Frederick Binkley     EMT/Paramedic/Firefighter 126863.190   
...        ...                 ...                           ...        ...   
111881  148646    Carolyn A Wilson     Human Services Technician      0.000   
111882  148648      Joann Anderson   Communications Dispatcher 2      0.000   
111883  148649         Leon Walker                     Custodian      0.000   
111884  148650       Roy I Tillery                     Custodian      0.000   
111885  148654           Joe Lopez    Counselor, Log Cabin Ranch      0.000   

        OvertimePay  OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0        220909.480 13126.310 44430.120 362844.660        407274.780  2012   
1             0.000 18974.110 69810.190 321552.110        391362.300  2012   
2        146415.320 78057.410 53102.290 336393.730        389496.020  2012   
3             0.000 17816.590 72047.880 314759.600        386807.480  2012   
4        192424.490 17917.180 44438.250 337204.860        381643.110  2012   
...             ...       ...       ...        ...               ...   ...   
111881        0.000     0.000     0.000      0.000             0.000  2014   
111882        0.000     0.000     0.000      0.000             0.000  2014   
111883        0.000     0.000     0.000      0.000             0.000  2014   
111884        0.000     0.000     0.000      0.000             0.000  2014   
111885        0.000  -618.130     0.000   -618.130          -618.130  2014   

        Notes            Agency  Status  NormalizedBasePay  \
0         NaN  b'San Francisco'       2              0.404   
1         NaN  b'San Francisco'       2              0.948   
2         NaN  b'San Francisco'       2              0.351   
3         NaN  b'San Francisco'       2              0.930   
4         NaN  b'San Francisco'       2              0.398   
...       ...               ...     ...                ...   
111881    NaN  b'San Francisco'       1              0.001   
111882    NaN  b'San Francisco'       1              0.001   
111883    NaN  b'San Francisco'       1              0.001   
111884    NaN  b'San Francisco'       1              0.001   
111885    NaN  b'San Francisco'       1              0.001   

        NormalizedOvertimePay  Normalized_Benefits  
0                       1.000                1.256  
1                       0.000                2.907  
2                       0.663                1.821  
3                       0.000                3.053  
4                       0.871                1.257  
...                       ...                  ...  
111881                  0.000               -1.634  
111882                  0.000               -1.634  
111883                  0.000               -1.634  
111884                  0.000               -1.634  
111885                  0.000               -1.634  

[111886 rows x 16 columns]